version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: lease-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: Asia/Shanghai
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - lease-network
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci

  minio:
    image: minio/minio:RELEASE.2024-06-13T22-53-53Z
    container_name: lease-minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - lease-network
    command: server /data --console-address ":9001"

  redis:
    image: redis:alpine
    container_name: lease-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - lease-network
    command: redis-server --appendonly yes

  web-admin:
    build:
      context: ./backend/admin
      dockerfile: Dockerfile
    container_name: lease-web-admin
    restart: unless-stopped
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${MYSQL_DATABASE}
      DB_USERNAME: root
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET: lease
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - minio
      - redis
    networks:
      - lease-network

  web-app:
    build:
      context: ./backend/app
      dockerfile: Dockerfile
    container_name: lease-web-app
    restart: unless-stopped
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${MYSQL_DATABASE}
      DB_USERNAME: root
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 1
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET: mobile-lease
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - minio
      - redis
    networks:
      - lease-network

  h5-frontend:
    build:
      context: ./frontend/h5-app
      dockerfile: Dockerfile
    container_name: lease-h5-frontend
    restart: unless-stopped
    networks:
      - lease-network

  admin-frontend:
    build:
      context: ./frontend/admin
      dockerfile: Dockerfile
    container_name: lease-admin-frontend
    restart: unless-stopped
    networks:
      - lease-network

  nginx:
    image: nginx:alpine
    container_name: lease-nginx
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
      - "8888:8888"
    depends_on:
      - web-admin
      - web-app
      - h5-frontend
      - admin-frontend
    networks:
      - lease-network

volumes:
  mysql_data:
    external: true
  minio_data:
    external: true
  redis_data:
    external: true

networks:
  lease-network:
    driver: bridge
